# Generated by Django 6.0.4 on 2026-04-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_budget',
        ),
    ]
